server:
  port: 8899
spring:
  redis:
    database: 0
    host: 192.168.0.12
    port: 6379
    password:
    timeout: 300
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0